pull_request_rules:
  - name: Automatic merge ⬇️ on approval and labeled ✔
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - label=wait-for-merging
    actions:
      merge:
        method: merge
