name: Deployment

on:
  issue_comment:
    types: [created]

jobs:
  start:
    runs-on: ubuntu-latest
    name: Extract number from comment
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Extract BACKEND_PR_NUMBER from comment
        id: extract_pr_number
        run: |
          echo '${{ fromJSON(steps.get-pr.outputs.result).head.sha }}'
          echo "helloo" >> README.md
          git config --global user.email "github@propte.io"
          git config --global user.name "Github Action"
          git add .
          git commit -m "Update readme from github action"
          git pull origin main
          git push origin main
