name: Deployment

on:
  issue_comment:
    types: [created]

jobs:
  start:
    runs-on: ubuntu-latest
    name: Extract number from comment

    steps:
      - name: Extract BACKEND_PR_NUMBER from comment
        id: extract_pr_number
        run: |
          echo "[+] COMMENT CONTENT: ${{ github.event.comment.body }}"
          BACKEND_PR_NUMBER=$(expr "x${{ github.event.comment.body }}" : '.*[^0-9]\([0-9]\{1,\}\)')
          echo "$BACKEND_PR_NUMBER"
